name: CI - build and test

on:                                
  push:
    branches: [ main, CI-setup ]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:                         
    - uses: actions/checkout@v2                   
    - name: Set up JDK 11                         
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew  
      run: chmod +x gradlew              
    - name: Build and test the plugin             
      timeout-minutes: 20
      run: ./gradlew build
    - name: Generate reports 
      run: ./gradlew reports
    - name: Generate report stats
      run: ./gradlew reportStats
    - name: Make the directory for gh-pages branch #Not needed?
      run: mkdir -p build/gh-pages
    - name: Go into the build directory
      run: 'cd build/; cp -r ./docs/ ./gh-pages/; cp -r ./reports/ ./gh-pages/; cp -r ./spotbugs/ ./gh-pages/; wget -O ./gh-pages/index.md https://raw.githubusercontent.com/elee006/CS350-Project/gh-pages/index.md; '
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop #https://github.com/s0/git-publish-subdir-action
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: build/gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}